name: Build

on:
  pull_request:
    branches: main

jobs:
  build:
    name: Build using swift
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: swift build
